server:
   port: 5555
zuul:
   ignored-services: '*'
   prefix: /api
   routes:
      configserver: /configs/**
      userservice: /authors/**
      blogcrud: /blogs/**

eureka:
   instance:
      preferIpAddress: true
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/

logging:
   level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.thoughtmechanix: DEBUG
      
management:
  endpoints:
    web:
      exposure:
#         include: refresh, info
         include: "*"